//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Face_Detect_System_Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonInfoForFaceRecEntities : DbContext
    {
        public PersonInfoForFaceRecEntities()
            : base("name=PersonInfoForFaceRecEntities")
        {
        }

        private static PersonInfoForFaceRecEntities _context;

        public static PersonInfoForFaceRecEntities GetContext()
        {
            if (_context == null)
            {
                _context = new PersonInfoForFaceRecEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PersonInfo> PersonInfo { get; set; }
    }
}
