//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Face_Detect_System_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfo
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Activity { get; set; }

        public string BirthdayFormat
        {
            get
            {

                return Birthday.ToShortDateString();
            }
        }

    }
}
